# Generated by Django 5.2.3 on 2025-06-28 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal category name (used in URLs)', max_length=254, unique=True)),
                ('friendly_name', models.CharField(blank=True, help_text='Display name for the category', max_length=254, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional category description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit - unique product identifier', max_length=254, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=254)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('rating', models.IntegerField(blank=True, help_text='Product rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image_url', models.URLField(blank=True, help_text='URL to product image', max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, help_text='Product image file', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active and visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this product should be featured')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'), models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'), models.Index(fields=['rating'], name='products_pr_rating_c3ba71_idx'), models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx')],
            },
        ),
    ]
