# Generated by Django 3.2.25 on 2025-06-25 23:43

from django.db import migrations
from django.utils.text import slugify

from home import models

def populate_slugs(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    for category in Category.objects.all():
        if category.slug == 'temp-slug':  
            category.slug = slugify(category.name)
            category.save()

class Migration(migrations.Migration):
    dependencies = [
        ('products', 'previous_migration_name'),  
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
    # products/models.py
slug = models.SlugField(unique=True, null=True)  # Add null=True temporarily