# Generated by Django 5.2.3 on 2025-06-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.CharField(blank=True, help_text='Product brand', max_length=254, null=True),
        ),
    ]
