# Generated by Django 5.2.3 on 2025-06-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_delivery',
            field=models.CharField(blank=True, help_text='Estimated delivery time', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(blank=True, help_text='Shipping information', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_status',
            field=models.CharField(blank=True, help_text='VAT status', max_length=254, null=True),
        ),
    ]
