# Generated by Django 5.2.3 on 2025-06-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, help_text='Stock status', max_length=254, null=True),
        ),
    ]
