# Generated by Django 5.2.3 on 2025-06-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='Warranty information', max_length=254, null=True),
        ),
    ]
