# Generated by Django 5.2.3 on 2025-06-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, help_text='Product availability', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility',
            field=models.CharField(blank=True, help_text='Device compatibility', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, help_text='Product condition', max_length=254, null=True),
        ),
    ]
