# Generated by Django 5.2.3 on 2025-06-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_availability_product_compatibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Product features', null=True),
        ),
    ]
