# Generated by Django 5.2.3 on 2025-06-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='includes',
            field=models.CharField(blank=True, help_text="What's included with the product", max_length=254, null=True),
        ),
    ]
