# Generated by Django 5.2.3 on 2025-06-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_type',
            field=models.CharField(blank=True, help_text='Display type', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='includes',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
