# Generated by Django 5.2.3 on 2025-06-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
