# Generated by Django 5.2.3 on 2025-06-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_repair_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tool_requirements',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
