# Generated by Django 5.2.3 on 2025-06-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_difficulty_product_install_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_required',
        ),
        migrations.AddField(
            model_name='product',
            name='color_accuracy',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
