# Generated by Django 5.2.3 on 2025-06-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_time_required_product_color_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_features',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
