# Generated by Django 5.2.3 on 2025-06-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_special_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
