# Generated by Django 5.2.3 on 2025-06-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_product_build_quality_product_cable_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='functions',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
