# Generated by Django 5.2.3 on 2025-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oem_equivalent',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
