# Generated by Django 5.2.3 on 2025-06-29 15:59

from django.db import migrations


from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('products', '0036_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254, null=True, blank=True),
        ),
    ]

