# Generated by Django 5.2.3 on 2025-06-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_category_name'),
        ('products', '0038_remove_name_unique'),
    ]

    operations = [
    ]
