# Generated by Django 5.2.3 on 2025-07-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_product_options_alter_product_name_and_more'),
    ]

    operations = [
    ]
