# Generated by Django 5.2.3 on 2025-07-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_category_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='accessories_included',
        ),
        migrations.RemoveField(
            model_name='product',
            name='advanced_tech',
        ),
        migrations.RemoveField(
            model_name='product',
            name='age_restrictions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='apple_specific',
        ),
        migrations.RemoveField(
            model_name='product',
            name='audio_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='audio_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='autofocus_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery_specs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='benchmark_scores',
        ),
        migrations.RemoveField(
            model_name='product',
            name='biometric_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='biometric_note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bluetooth_version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera_specs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cellular_bands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='charging_technology',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_temp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='comfort_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='competitor_comparison',
        ),
        migrations.RemoveField(
            model_name='product',
            name='connector_specs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='connectors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='construction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='curved_display_specs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_optimization',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_technology',
        ),
        migrations.RemoveField(
            model_name='product',
            name='distribution_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='durability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='encryption_support',
        ),
        migrations.RemoveField(
            model_name='product',
            name='environmental',
        ),
        migrations.RemoveField(
            model_name='product',
            name='environmental_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flash_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='galaxy_optimization',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gaming_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gaming_optimized',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gps_accuracy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='haptic_support',
        ),
        migrations.RemoveField(
            model_name='product',
            name='humidity_tolerance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_stabilization',
        ),
        migrations.RemoveField(
            model_name='product',
            name='included_accessories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key_applications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lens_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='market_position',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_tech',
        ),
        migrations.RemoveField(
            model_name='product',
            name='microphone_specs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mtbf_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nfc_support',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oneplus_specific',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operating_temperature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='optical_properties',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_contents',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_includes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='performance_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='performance_metrics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='platform_compatibility',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protection_levels',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protection_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protection_specs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality_marks',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recycling_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='regulatory_compliance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_years',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reliability_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='safety_certifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='safety_warnings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_channel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_protection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='security_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shock_resistance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='smart_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='speaker_specs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_editions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stand_angles',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stand_functionality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_temperature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stress_test_results',
        ),
        migrations.RemoveField(
            model_name='product',
            name='support_contact',
        ),
        migrations.RemoveField(
            model_name='product',
            name='support_hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_market',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='touch_technology',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unboxing_experience',
        ),
        migrations.RemoveField(
            model_name='product',
            name='universal_compatibility',
        ),
        migrations.RemoveField(
            model_name='product',
            name='use_cases',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vibration_resistance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_recording',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_coverage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_terms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water_resistance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wifi_standards',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wireless_features',
        ),
        migrations.AlterField(
            model_name='product',
            name='aftermarket_part',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='anti_fingerprint',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brightness_level',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='build_quality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cable_length',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='certification',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='certification_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='charging_speed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_accuracy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_gamut',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_options',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='compatibility',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='compliance',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='component_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='connectivity_options',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='connector_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='contrast_ratio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_rating',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_transfer_rate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_tier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='difficulty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discontinuation_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='documentation_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durability_features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durability_rating',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='efficiency_rating',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='environmental_specs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_delivery',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='excludes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='faq_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='functions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='glass_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hdr_support',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='includes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_level',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lifecycle_stage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='market',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='market_segment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='msrp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oem_equivalent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oem_part',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oleophobic_coating',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='performance_specs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pixel_density',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity_rank',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='port_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_output',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_requirements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promoted',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='protection_features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_terms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality_assurance',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality_rating',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='repair_difficulty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='repair_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='replacement_for',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='replacement_parts',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='response_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_rank',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_requirements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='support_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_audience',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_specs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='testing_standards',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tool_requirements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tools_needed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='touch_sensitivity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_manual',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_guide',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewing_angle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='voltage_rating',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
