# Generated by Django 5.2.3 on 2025-07-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_remove_product_accessories_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='optical_properties',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
