# Generated by Django 5.2.3 on 2025-07-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_add_optical_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_contents',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
