# Generated by Django 5.2.3 on 2025-07-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_add_package_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='technology',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
