# Generated by Django 5.2.3 on 2025-07-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backlight_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brightness',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
