# Generated by Django 5.2.3 on 2025-07-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_add_all_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='connectors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
