# Generated by Django 5.2.3 on 2025-07-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_add_fixture_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fixture_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
