# Generated by Django 5.2.3 on 2025-07-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_add_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_technology',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
